apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: meal-planner-agent
  labels:
    cloud.googleapis.com/location: us-central1
spec:
  template:
    spec:
      containers:
      - image: gcr.io/your-project/meal-planner-agent:latest
        ports:
        - containerPort: 8000
        env:
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: gemini-api-key
              key: key
        resources:
          limits:
            memory: 1Gi
            cpu: 1000m