# =============================
# SmartGeminiTools (Memory Ready)
# =============================

import os
import logging
import random
import json
from typing import Dict, Any

from tools.memory_tools import AdvancedMemoryTools
memory = AdvancedMemoryTools()  # FULL MEMORY ACCESS

logger = logging.getLogger("GeminiTools")
logger.addHandler(logging.NullHandler())

try:
    import google.generativeai as genai
    HAS_GENAI = True
except Exception:
    HAS_GENAI = False


class SmartGeminiTools:
    def __init__(self, api_key=None):
        self.api_key = api_key or os.getenv("GEMINI_API_KEY")
        self.model = None
        self._init_model()

    # -----------------------------
    def _init_model(self):
        if HAS_GENAI and self.api_key:
            try:
                genai.configure(api_key=self.api_key)
                try:
                    self.model = genai.GenerativeModel("gemini-1.5-flash")
                except Exception:
                    self.model = None
                if self.model:
                    logger.info("Gemini model loaded successfully")
            except Exception:
                self.model = None
        else:
            self.model = None

    # -----------------------------
    def generate_varied_meal_plan(self, prefs: Dict[str, Any]) -> Dict[str, Any]:

        prefs = self._normalize_prefs(prefs)
        user_id = prefs.get("user_id", "unknown")

        # Try Gemini first
        if self.model:
            try:
                g = self._generate_gemini(prefs)
                if g:
                    weekly = g["meal_plan"]
                    shopping = g["shopping_list"]
                    analysis = g["analysis"]

                    # SAVE MEMORY
                    memory.save_meal_feedback(
                        user_id,
                        weekly,
                        {"rating": 5, "comments": "Generated by Gemini"}
                    )

                    return g
            except Exception:
                pass

        # Local fallback
        weekly = self._fallback_generate(prefs)
        shopping = self._shopping(weekly)
        analysis = self._nutrition(weekly)

        # SAVE MEMORY
        memory.save_meal_feedback(
            user_id,
            weekly,
            {"rating": 5, "comments": "Generated by fallback"}
        )

        return {
            "meal_plan": weekly,
            "shopping_list": shopping,
            "analysis": analysis
        }

    # -----------------------------
    def _normalize_prefs(self, p: Dict[str, Any]):
        return {
            "user_id": p.get("user_id") or "unknown",
            "diet_type": (p.get("diet_type") or "").lower(),
            "calorie_target": int(p.get("calorie_target") or 2000),
            "allergies": [a.lower().strip() for a in (p.get("allergies") or [])],
            "cuisine_preference": (p.get("cuisine_preference") or "any").lower(),
            "goals": p.get("goals") or []
        }

    # -----------------------------
    def _generate_gemini(self, prefs):
        prompt = (
            "Return JSON ONLY:\n"
            "{\n"
            "  \"meal_plan\": {\n"
            "    \"Monday\": {\"meals\": {\"breakfast\": {}, \"lunch\": {}, \"dinner\": {}}, \"total_calories\": 0},\n"
            "    \"Tuesday\": {\"meals\": {\"breakfast\": {}, \"lunch\": {}, \"dinner\": {}}, \"total_calories\": 0},\n"
            "    \"Wednesday\": {\"meals\": {\"breakfast\": {}, \"lunch\": {}, \"dinner\": {}}, \"total_calories\": 0},\n"
            "    \"Thursday\": {\"meals\": {\"breakfast\": {}, \"lunch\": {}, \"dinner\": {}}, \"total_calories\": 0},\n"
            "    \"Friday\": {\"meals\": {\"breakfast\": {}, \"lunch\": {}, \"dinner\": {}}, \"total_calories\": 0},\n"
            "    \"Saturday\": {\"meals\": {\"breakfast\": {}, \"lunch\": {}, \"dinner\": {}}, \"total_calories\": 0},\n"
            "    \"Sunday\": {\"meals\": {\"breakfast\": {}, \"lunch\": {}, \"dinner\": {}}, \"total_calories\": 0}\n"
            "  },\n"
            "  \"shopping_list\": {},\n"
            "  \"analysis\": {}\n"
            "}\n"
        )

        txt = self.model.generate_content(prompt).text
        start = txt.find("{")
        end = txt.rfind("}") + 1
        return json.loads(txt[start:end])

    # -----------------------------
    # FALLBACK ENGINE
    # -----------------------------
    def _fallback_generate(self, prefs):

        veg = prefs["diet_type"] == "vegetarian"
        allergies = set(prefs["allergies"])

        def safe(recipe):
            for ing in recipe["ingredients"]:
                if ing.lower() in allergies:
                    return False
            if veg and any(x in recipe["name"].lower() for x in ["chicken", "fish", "egg"]):
                return False
            return True

        DB = {
            "breakfast": [
                {"name": "Masala Oats", "calories": 250, "protein": 12, "carbs": 40, "fat": 6, "prep_time": 10,
                 "ingredients": {"oats": 50, "vegetables": 100}},
                {"name": "Paneer Paratha", "calories": 380, "protein": 18, "carbs": 45, "fat": 15, "prep_time": 20,
                 "ingredients": {"paneer": 100, "whole_wheat_flour": 80}},
                {"name": "Fruit Bowl", "calories": 220, "protein": 8, "carbs": 52, "fat": 1, "prep_time": 5,
                 "ingredients": {"fruits": 150}},
                {"name": "Egg Omelette", "calories": 260, "protein": 20, "carbs": 3, "fat": 18, "prep_time": 10,
                 "ingredients": {"eggs": 2, "onions": 30}},
                {"name": "Chicken Omelette", "calories": 310, "protein": 28, "carbs": 5, "fat": 20, "prep_time": 12,
                 "ingredients": {"eggs": 2, "chicken": 60}}
            ],

            "lunch": [
                {"name": "Dal Rice", "calories": 450, "protein": 22, "carbs": 75, "fat": 12, "prep_time": 25,
                 "ingredients": {"rice": 150, "dal": 100}},
                {"name": "Rajma Chawal", "calories": 470, "protein": 24, "carbs": 70, "fat": 13, "prep_time": 35,
                 "ingredients": {"rajma": 120, "rice": 150}},
                {"name": "Veg Biryani", "calories": 440, "protein": 18, "carbs": 80, "fat": 14, "prep_time": 30,
                 "ingredients": {"rice": 160, "vegetables": 200}},
                {"name": "Chicken Curry & Rice", "calories": 520, "protein": 35, "carbs": 60, "fat": 14, "prep_time": 40,
                 "ingredients": {"chicken": 150, "rice": 150}},
                {"name": "Fish Masala + Rice", "calories": 480, "protein": 32, "carbs": 55, "fat": 12, "prep_time": 35,
                 "ingredients": {"fish": 150, "rice": 140}}
            ],

            "dinner": [
                {"name": "Veg Khichdi", "calories": 380, "protein": 15, "carbs": 60, "fat": 10, "prep_time": 20,
                 "ingredients": {"rice": 100, "dal": 80}},
                {"name": "Paneer Curry + Roti", "calories": 480, "protein": 25, "carbs": 50, "fat": 20, "prep_time": 30,
                 "ingredients": {"paneer": 150, "roti": 2}},
                {"name": "Veg Soup", "calories": 300, "protein": 10, "carbs": 40, "fat": 5, "prep_time": 15,
                 "ingredients": {"vegetables": 250}},
                {"name": "Grilled Chicken + Rice", "calories": 500, "protein": 38, "carbs": 60, "fat": 10, "prep_time": 30,
                 "ingredients": {"chicken": 180, "rice": 120}},
                {"name": "Fish Fry + Rice", "calories": 480, "protein": 30, "carbs": 60, "fat": 12, "prep_time": 25,
                 "ingredients": {"fish": 150, "rice": 120}}
            ]
        }

        used = {"breakfast": set(), "lunch": set(), "dinner": set()}
        days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]

        weekly = {}

        for day in days:
            daily = {"meals": {}}
            total = 0

            for meal in ["breakfast", "lunch", "dinner"]:
                pool = [x for x in DB[meal] if safe(x) and x["name"] not in used[meal]]

                if not pool:
                    used[meal].clear()
                    pool = [x for x in DB[meal] if safe(x)]

                selected = random.choice(pool)
                used[meal].add(selected["name"])

                daily["meals"][meal] = selected
                total += selected["calories"]

            daily["total_calories"] = total
            weekly[day] = daily

        return weekly

    # -----------------------------
    def _shopping(self, plan):
        bag = {}

        for day in plan.values():
            for meal in day["meals"].values():
                for ing, qty in meal["ingredients"].items():
                    k = ing.lower()
                    bag[k] = bag.get(k, 0) + float(qty)

        out = {}
        for k, v in bag.items():
            if v <= 5:
                out[k] = int(v * 60)
            elif "egg" in k:
                out[k] = int(v * 60)
            else:
                out[k] = int(v)

        return out

    # -----------------------------
    def _nutrition(self, plan):
        tc = 0
        tp = 0
        c = 0

        for day in plan.values():
            for meal in day["meals"].values():
                tc += meal.get("calories", 0)
                tp += meal.get("protein", 0)
                c += 1

        return {
            "avg_daily_calories": int(tc / 7),
            "avg_daily_protein": int(tp / 7),
            "total_meals": c
        }
